import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parseRegisterPage, joinBilingual, normalizeAddress } from "../src/parser";

const enHtml = readFileSync(join(__dirname, "fixtures/eaf_en_sample.html"), "utf-8");
const tcHtml = readFileSync(join(__dirname, "fixtures/eaf_tc_sample.html"), "utf-8");

describe("parseRegisterPage", () => {
  it("parses all fixture rows (EN)", () => {
    const rows = parseRegisterPage(enHtml);
    expect(rows.length).toBe(60);
  });
  it("parses all fixture rows (TC)", () => {
    const rows = parseRegisterPage(tcHtml);
    expect(rows.length).toBe(60);
  });
  it("extracts Chinese names from the TC page", () => {
    const rows = parseRegisterPage(tcHtml);
    expect(rows.some((r) => /[一-鿿]/.test(r.name) || /[一-鿿]/.test(r.address))).toBe(true);
  });
  it("extracts known first EN row fields", () => {
    const rows = parseRegisterPage(enHtml);
    const r = rows[0];
    expect(r.address).toContain("Li Yuen Street East");
    expect(r.expiryDate).toBe("13/11/2028");
    expect(r.euiMj).toBe(77.98);
    expect(r.reaNo).toBe("EA00539G");
    expect(r.prevExpiryDate).toBeNull();
    expect(r.isDemolished).toBe(false);
  });
  it("detects demolished flag from TC prefix", () => {
    const rows = parseRegisterPage(tcHtml);
    const demolished = rows.filter((r) => r.isDemolished);
    expect(demolished.length).toBeGreaterThan(0);
    expect(demolished[0].name).not.toContain("已拆卸");
  });
  it("throws loudly when layout changes", () => {
    expect(() => parseRegisterPage("<html><body>nothing here</body></html>")).toThrow(/layout changed/);
  });
});

describe("joinBilingual", () => {
  it("joins EN and TC rows despite different sort orders", () => {
    const en = parseRegisterPage(enHtml);
    const tc = parseRegisterPage(tcHtml);
    const joined = joinBilingual(en, tc);
    expect(joined.length).toBe(en.length);
    const matched = joined.filter((j) => j.tc !== null);
    // TC fixture was generated by selecting the TC rows whose composite keys match the
    // EN fixture, so every row must join (the full live register joins at 100% too)
    expect(matched.length).toBe(en.length);
    for (const j of matched) {
      expect(j.tc!.reaNo).toBe(j.en.reaNo);
      expect(j.tc!.expiryDate).toBe(j.en.expiryDate);
    }
  });
  it("never assigns one TC row to two EN rows", () => {
    const en = parseRegisterPage(enHtml);
    const tc = parseRegisterPage(tcHtml);
    const joined = joinBilingual(en, tc);
    const used = joined.filter((j) => j.tc).map((j) => j.tc);
    expect(new Set(used).size).toBe(used.length);
  });
});

describe("normalizeAddress", () => {
  it("is case/space/punctuation insensitive", () => {
    expect(normalizeAddress("1-2 Li Yuen Street East,  Hong Kong")).toBe(
      normalizeAddress("1-2 LI YUEN STREET EAST. HONG KONG"),
    );
  });
});
